# Generated by Django 5.1.5 on 2025-02-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
