# Generated by Django 5.1.5 on 2025-02-28 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_genre_name_alter_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
