# Generated by Django 5.1.3 on 2025-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0008_song_total_plays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='total_plays',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество прослушиваний'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_at', 'total_plays'], name='store_song_created_83f3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email'], name='store_user_usernam_83452b_idx'),
        ),
    ]
