# Generated by Django 5.1.3 on 2025-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_song_total_plays_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='store_song_created_83f3f5_idx',
        ),
        migrations.AlterField(
            model_name='song',
            name='total_plays',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_at'], name='store_song_created_c9f802_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['total_plays'], name='store_song_total_p_a9b25e_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['author', 'created_at'], name='store_song_author__145a9a_idx'),
        ),
    ]
